/** Regenerate the embedded Goated-Flash-Free server module from the vendored python. */
const py = await Bun.file("src/vendor/gemini-web2api/gemini_web2api.py").text();
await Bun.write(
  "src/vendor/flashServer.ts",
  "// GENERATED by scripts/gen-flash.ts — edit src/vendor/gemini-web2api/gemini_web2api.py instead.\n" +
  "export const FLASH_SERVER_PY = " + JSON.stringify(py) + ";\n",
);
console.log("flashServer.ts generated:", py.length, "bytes");
