/**
 * Regenerate src/web/assets.gen.ts from the UI sources. Run after editing
 * src/web/index.html or the vendored marked build:
 *
 *   bun run scripts/gen-web-assets.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dir, "..");
const html = readFileSync(join(root, "src/web/index.html"), "utf8");
const marked = readFileSync(join(root, "src/web/vendor/marked.umd.js"), "utf8");

const out =
  "// Generated by scripts/gen-web-assets.ts — embedded UI for `goat web`.\n" +
  "// Edit src/web/index.html, then re-run the generator. Do not hand-edit.\n" +
  "export const UI_HTML = " + JSON.stringify(html) + ";\n" +
  "export const MARKED_JS = " + JSON.stringify(marked) + ";\n";

writeFileSync(join(root, "src/web/assets.gen.ts"), out, "utf8");
console.log(`wrote src/web/assets.gen.ts (${out.length} bytes)`);
